### ISSUE TITLE
Galaxy Requires newer version of bcftools

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/docker-galaxy-requirements#3]

**Comment by jmchilton** [comment]
Once updated here, need to rebuild the Galaxy test image.

**Comment by bgruening** [comment]
Version 1.2 should be enough, isn't it? I think this one can be closed.

**Comment by bgruening** [comment]
Fixed in https://github.com/galaxyproject/docker-galaxy-requirements/pull/4
