### ISSUE TITLE
What does this repo do? What is it for? 

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/docker-galaxy-requirements#5]
I personally would appreciate it a great deal if someone could describe just a little bit (in the readme) what this does. 

My major question is why the 16.04 release of docker-galaxy-stable relies on ubuntu 14.04 image in this repo... @bgruening

**Comment by bgruening** [comment]
`16.04` is the Galaxy release not the Ubuntu release. All Galaxy images are based on Ubuntu `14.04`.

**Comment by bgruening** [comment]
is this better? https://github.com/galaxyproject/docker-galaxy-requirements/pull/6

**Comment by martenson** [comment]
@zfrenchee It is my understanding that this repo is an attempt to formalize (via Dockerfile definition) what software is expected to be present on the machine that will install a Tool Shed dependency recipe. Useful especially for tool devs.

**Comment by alexlenail** [comment]
@martenson I see. So it's separate from docker-galaxy-stable just for documentation purposes, really?

**Comment by martenson** [comment]
@zfrenchee quite the opposite, it is the base image for that

**Comment by bgruening** [comment]
I have updated the readme.

**Comment by bgruening** [comment]
Thanks @zfrenchee!
